from config_definitions.organisation_type_map_config import ORGANISATION_TYPE_MAP_CONFIG
from config_definitions.technologies_config import TECHNOLOGIES_CONFIG
from config_definitions.test_config import TEST_CONFIG

CONFIG_DEFINITIONS = [TEST_CONFIG, TECHNOLOGIES_CONFIG, ORGANISATION_TYPE_MAP_CONFIG]
