from pipelineFramework import Configuration, LocalisationString

ORGANISATION_TYPE_MAP_CONFIG = Configuration(
    "organisation_type",
    LocalisationString("Organisation Types Mapper", "Organisation Types Mapper"),
    [
        {
            "name": "Universities",
            "description": "",
            "mapTo": "UNIVERSITY",
            "keywords": [
                r"(?<!\w)universit(?:y|ies)(?!\w)(?!\s+of\s+applied\s+sciences)",
                r"(?<!\w)universit(?:ä|ae)t(?:en)?(?!\w)",
                r"(?<!\w)universitat(?:ea)?(?!\w)",
                r"(?<!\w)universit(?:é|e)s?(?!\w)",
                r"(?<!\w)universidad(?:es)?(?!\w)",
                r"(?<!\w)universidades?(?!\w)",
                r"(?<!\w)universit(?:à|a)(?!\w)",
                r"(?<!\w)universiteit(?!\w)",
                r"(?<!\w)universitet(?:et|as|i)?(?!\w)",
                r"(?<!\w)universitas(?!\w)",
                r"(?<!\w)uniwersytet\w*(?!\w)",
                r"(?<!\w)univerzit(?:a|y|et)\w*(?!\w)",
                r"(?<!\w)univerza(?!\w)",
                r"(?<!\w)(?:ü|u)niversite(?:si)?(?!\w)",
                r"(?<!\w)\w*egyetem\w*(?!\w)",
                r"(?<!\w)yliopisto\w*(?!\w)",
                r"(?<!\w)πανεπιστ\w*(?!\w)",
                r"(?<!\w)университет\w*(?!\w)",
                r"大学",
                r"대학교?",
                r"(?<!\w)جامعة(?!\w)",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Fachhochschule",
            "description": "",
            "mapTo": "FACHHOCHSCHULE",
            "keywords": [
                r"(?<!\w)fachhochschule[nr]?(?!\w)",
                r"(?<!\w)fh(?!\w)",
                r"(?<!\w)universit(?:y|ies)\s+of\s+applied\s+sciences(?!\w)",
                r"(?<!\w)hochschule\s+f(?:ü|ue)r\s+angewandte\s+wissenschaften(?!\w)",
                r"(?<!\w)hogeschool(?!\w)",
                r"(?<!\w)haute\s+(?:é|e)cole(?!\w)",
                r"(?<!\w)escuela\s+universitaria\s+polit(?:é|e)cnica(?!\w)",
                r"(?<!\w)ammattikorkeakoulu(?!\w)",
                r"(?<!\w)yrkesh(?:ö|o)gskola(?!\w)",
                r"応用科学大学",
                r"应用科学大学",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Research Institute",
            "description": "",
            "mapTo": "RESEARCH_INSTITUTE",
            "keywords": [
                r"(?<!\w)research\s+institut(?:e|es|ion|ions)(?!\w)",
                r"(?<!\w)research\s+cent(?:er|re)s?(?!\w)",
                r"(?<!\w)research\s+laborator(?:y|ies)(?!\w)",
                r"(?<!\w)forschungsinstitut(?:e|s)?(?!\w)",
                r"(?<!\w)forschungszentr(?:um|en)(?!\w)",
                r"(?<!\w)forschungseinrichtung(?:en)?(?!\w)",
                r"(?<!\w)forschungsgesellschaft(?:en)?(?!\w)",
                r"(?<!\w)forschungslabor(?:s|e)?(?!\w)",
                r"(?<!\w)institut\s+de\s+recherche(?!\w)",
                r"(?<!\w)centre\s+de\s+recherche(?!\w)",
                r"(?<!\w)instituto\s+de\s+investigaci(?:ó|o)n(?!\w)",
                r"(?<!\w)centro\s+de\s+investigaci(?:ó|o)n(?!\w)",
                r"(?<!\w)instituto\s+de\s+investiga(?:ç|c)(?:ã|a)o(?!\w)",
                r"(?<!\w)istituto\s+di\s+ricerca(?!\w)",
                r"(?<!\w)centro\s+di\s+ricerca(?!\w)",
                r"(?<!\w)onderzoeksinstituut(?!\w)",
                r"(?<!\w)instytut\s+badawczy(?!\w)",
                r"(?<!\w)v(?:ý|y)zkumn(?:ý|y)\s+(?:ú|u)stav(?!\w)",
                r"(?<!\w)ara(?:ş|s)t(?:ı|i)rma\s+enstit(?:ü|u)s(?:ü|u)(?!\w)",
                r"(?<!\w)научно-исследовательский\w*(?!\w)",
                r"(?<!\w)исследовательский\s+институт(?!\w)",
                r"研究所",
                r"研究院",
                r"研究センター",
                r"연구(?:소|원)",
                r"(?<!\w)academy\s+of\s+sciences(?!\w)",
                r"(?<!\w)akademie\s+der\s+wissenschaften(?!\w)",
                r"(?<!\w)acad(?:é|e)mie\s+des\s+sciences(?!\w)",
                r"(?<!\w)academia\s+de\s+ciencias(?!\w)",
                r"(?<!\w)accademia\s+delle\s+scienze(?!\w)",
                r"(?<!\w)akademia\s+nauk(?!\w)",
                r"(?<!\w)академия\s+наук(?!\w)",
                r"科学院",
                r"(?<!\w)max[-\s]planck(?!\w)",
                r"(?<!\w)fraunhofer(?!\w)",
                r"(?<!\w)helmholtz(?!\w)",
                r"(?<!\w)leibniz(?!\w)",
                r"(?<!\w)cnrs(?!\w)",
                r"(?<!\w)inserm(?!\w)",
                r"(?<!\w)inria(?!\w)",
                r"(?<!\w)csic(?!\w)",
                r"(?<!\w)csiro(?!\w)",
                r"(?<!\w)sintef(?!\w)",
                r"(?<!\w)imec(?!\w)",
                r"(?<!\w)riken(?!\w)",
                r"(?<!\w)cern(?!\w)",
                r"(?<!\w)tno(?!\w)",
                r"(?<!\w)vtt(?!\w)",
                r"(?<!\w)aist(?!\w)",
                r"(?<!\w)cea(?!\w)",
                r"(?<!\w)cnr(?!\w)",
                r"(?<!\w)austrian\s+institute\s+of\s+technology(?!\w)",
                r"(?<!\w)ait(?!\w)",
                r"(?<!\w)joanneum\s+research(?!\w)",
                r"(?<!\w)silicon\s+austria\s+labs(?!\w)",
                r"(?<!\w)ludwig\s+boltzmann(?!\w)",
                r"(?<!\w)institute\s+of\s+science\s+and\s+technology\s+austria(?!\w)",
                r"(?<!\w)ist\s+austria(?!\w)",
                r"(?<!\w)iiasa(?!\w)",
                r"(?<!\w)salzburg\s+research(?!\w)",
                r"(?<!\w)know[-\s]?center(?!\w)",
                r"(?<!\w)institut\s+f(?:ü|ue)r\s+h(?:ö|oe)here\s+studien(?!\w)",
                r"(?<!\w)(?:ö|oe)sterreichisches\s+institut\s+f(?:ü|ue)r\s+wirtschaftsforschung(?!\w)",
                r"(?<!\w)wifo(?!\w)",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Single Researcher",
            "description": "",
            "mapTo": "SINGLE_RESEARCHER",
            "keywords": [
                r"(?<!\w)univ\.?[-\s]*prof\.?(?!\w)",
                r"(?<!\w)ass(?:oc)?\.?[-\s]*prof\.?(?!\w)",
                r"(?<!\w)prof\.(?!\w)",
                r"(?<!\w)priv\.?[-\s]*doz\.?(?!\w)",
                r"(?<!\w)dr\.(?!\w)",
                r"(?<!\w)dr\.?in(?!\w)",
                r"(?<!\w)dr\.\s*(?:med|techn|phil|iur|nat)\.(?!\w)",
                r"(?<!\w)dr\.\s*rer\.\s*nat\.(?!\w)",
                r"(?<!\w)dipl\.?[-\s]*ing\.?(?!\w)",
                r"(?<!\w)mag\.a?(?!\w)",
                r"(?<!\w)ph\.?\s?d\.?(?!\w)",
                r"(?<!\w)m\.\s?sc\.?(?!\w)",
                r"(?<!\w)b\.\s?sc\.?(?!\w)",
                r"(?<!\w)einzelperson(?!\w)",
                r"(?<!\w)privatperson(?!\w)",
                r"(?<!\w)nat(?:ü|ue)rliche\s+person(?!\w)",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Non Profit Organisation",
            "description": "",
            "mapTo": "NON_PROFIT",
            "keywords": [
                r"(?<!\w)gemeinn(?:ü|ue)tzig\w*(?!\w)",
                r"(?<!\w)ggmbh(?!\w)",
                r"(?<!\w)non[-\s]?profit(?!\w)",
                r"(?<!\w)not[-\s]for[-\s]profit(?!\w)",
                r"(?<!\w)charit(?:y|ies|able)(?!\w)",
                r"(?<!\w)eingetragener\s+verein(?!\w)",
                r"(?<!\w)e\.\s*v\.(?!\w)",
                r"(?<!\w)asbl(?!\w)",
                r"(?<!\w)vzw(?!\w)",
                r"(?<!\w)onlus(?!\w)",
                r"(?<!\w)ngo(?!\w)",
                r"(?<!\w)non[-\s]govern(?:ment|mental)(?!\w)",
                r"(?<!\w)\w*stiftung(?:en)?(?!\w)",
                r"(?<!\w)foundation(?!\w)",
                r"(?<!\w)fondation(?!\w)",
                r"(?<!\w)fundaci(?:ó|o)n(?!\w)",
                r"(?<!\w)funda(?:ç|c)(?:ã|a)o(?!\w)",
                r"(?<!\w)fondazione(?!\w)",
                r"(?<!\w)stichting(?!\w)",
                r"(?<!\w)fundacja(?!\w)",
                r"(?<!\w)nadace(?!\w)",
                r"(?<!\w)alap(?:í|i)tv(?:á|a)ny(?!\w)",
                r"(?<!\w)s(?:ä|a)(?:ä|a)ti(?:ö|o)(?!\w)",
                r"(?<!\w)vakf(?:ı|i)(?!\w)",
                r"(?<!\w)фонд\w*(?!\w)",
                r"財団",
                r"基金会",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Lobby Organisations",
            "description": "",
            "mapTo": "LOBBY",
            "keywords": [
                r"(?<!\w)lobby\w*(?!\w)",
                r"(?<!\w)interessens?vertretung(?:en)?(?!\w)",
                r"(?<!\w)interessengemeinschaft(?:en)?(?!\w)",
                r"(?<!\w)industriellenvereinigung(?!\w)",
                r"(?<!\w)\w*verb(?:a|ä)nd\w*(?!\w)",
                r"(?<!\w)(?:wirtschafts|arbeiter|landwirtschafts|(?:ä|ae)rzte|apotheker|rechtsanwalts|notariats|handels|industrie)kammer(?!\w)",
                r"(?<!\w)chamber\s+of\s+(?:commerce|labour|labor|industry)(?!\w)",
                r"(?<!\w)chambre\s+de\s+commerce(?!\w)",
                r"(?<!\w)c(?:á|a)mara\s+de\s+comercio(?!\w)",
                r"(?<!\w)camera\s+di\s+commercio(?!\w)",
                r"(?<!\w)(?:trade|industry|business|professional)\s+association(?!\w)",
                r"(?<!\w)advocacy(?!\w)",
                r"(?<!\w)\w*gewerkschaft\w*(?!\w)",
                r"(?<!\w)(?:trade|labour|labor)\s+union(?!\w)",
                r"(?<!\w)syndicat(?!\w)",
                r"(?<!\w)sindicato(?!\w)",
                r"(?<!\w)sindacato(?!\w)",
                r"(?<!\w)vakbond(?!\w)",
                r"(?<!\w)профсоюз\w*(?!\w)",
                r"経済団体連合会",
                r"行业协会",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Public Institution",
            "description": "",
            "mapTo": "PUBLIC_INSTITUTION",
            "keywords": [
                r"(?<!\w)\w*ministeri(?:um|en)(?!\w)",
                r"(?<!\w)ministry(?!\w)",
                r"(?<!\w)minist(?:è|e)re(?!\w)",
                r"(?<!\w)ministerio(?!\w)",
                r"(?<!\w)ministero(?!\w)",
                r"(?<!\w)ministerie(?!\w)",
                r"(?<!\w)ministerstwo(?!\w)",
                r"(?<!\w)министерство(?!\w)",
                r"省庁",
                r"(?<!\w)bundeskanzleramt(?!\w)",
                r"(?<!\w)\w*bundesamt(?:es)?(?!\w)",
                r"(?<!\w)(?:bundes|landes)anstalt(?!\w)",
                r"(?<!\w)(?:bundes|landes|stadt)?regierung(?!\w)",
                r"(?<![\w-])government(?:al)?(?!\w)",
                r"(?<!\w)gouvernement(?!\w)",
                r"(?<!\w)gobierno(?!\w)",
                r"(?<!\w)governo(?!\w)",
                r"(?<!\w)overheid(?!\w)",
                r"(?<!\w)правительство(?!\w)",
                r"政府",
                r"(?<!\w)\w*beh(?:ö|oe)rde(?:n)?(?!\w)",
                r"(?<!\w)public\s+authority(?!\w)",
                r"(?<!\w)federal\s+(?:office|agency|ministry)(?!\w)",
                r"(?<!\w)national\s+agency(?!\w)",
                r"(?<!\w)magistrat(?!\w)",
                r"(?<!\w)stadtverwaltung(?!\w)",
                r"(?<!\w)(?:stadt|markt|orts)gemeinde(?!\w)",
                r"(?<!\w)gemeindeamt(?!\w)",
                r"(?<!\w)bezirkshauptmannschaft(?!\w)",
                r"(?<!\w)municipalit(?:y|ies|é|e)(?!\w)",
                r"(?<!\w)city\s+council(?!\w)",
                r"(?<!\w)mairie(?!\w)",
                r"(?<!\w)ayuntamiento(?!\w)",
                r"(?<!\w)comune\s+di(?!\w)",
                r"(?<!\w)nationalbibliothek(?!\w)",
                r"(?<!\w)national\s+library(?!\w)",
                r"(?<!\w)(?:staats|bundes|landes)archiv(?:s|es)?(?!\w)",
                r"(?<!\w)national\s+archives?(?!\w)",
            ],
            "limitToDataSource": ["FWF"],
        },
        {
            "name": "Company",
            "description": "",
            "mapTo": "COMPANY",
            "keywords": [
                r"(?<!\w)gmbh(?!\w)",
                r"(?<!\w)\w*ges(?:ellschaft)?\s*m\.?\s*b\.?\s*h\.?(?!\w)",
                r"(?<!\w)aktiengesellschaft(?!\w)",
                r"(?<!\w)ag(?!\w)",
                r"(?<!\w)og(?!\w)",
                r"(?<!\w)kg(?!\w)",
                r"(?<!\w)ohg(?!\w)",
                r"(?<!\w)e\.\s*u\.(?!\w)",
                r"(?<!\w)limited(?!\w)",
                r"(?<!\w)ltd\.?(?!\w)",
                r"(?<!\w)plc(?!\w)",
                r"(?<!\w)incorporated(?!\w)",
                r"(?<!\w)inc\.?(?!\w)",
                r"(?<!\w)corp(?:oration)?\.?(?!\w)",
                r"(?<!\w)l\.?l\.?c\.?(?!\w)",
                r"(?<!\w)s\.\s*a\.(?!\w)",
                r"(?<!\w)s\.\s*a\.\s*s\.(?!\w)",
                r"(?<!\w)s(?:\.|\s)*(?:à|a)(?:\.|\s)*r(?:\.|\s)*l\.?(?!\w)",
                r"(?<!\w)sarl(?!\w)",
                r"(?<!\w)s\.\s*r\.\s*l\.(?!\w)",
                r"(?<!\w)srl(?!\w)",
                r"(?<!\w)s\.\s*p\.\s*a\.(?!\w)",
                r"(?<!\w)b\.\s*v\.(?!\w)",
                r"(?<!\w)n\.\s*v\.(?!\w)",
                r"(?<!\w)a/s(?!\w)",
                r"(?<!\w)aps(?!\w)",
                r"(?<!\w)oyj?(?!\w)",
                r"(?<!\w)sp\.\s*z\s*o\.\s*o\.(?!\w)",
                r"(?<!\w)s\.\s*r\.\s*o\.(?!\w)",
                r"(?<!\w)d\.\s*o\.\s*o\.(?!\w)",
                r"(?<!\w)kft\.?(?!\w)",
                r"(?<!\w)zrt\.?(?!\w)",
                r"(?<!\w)pte\.?\s*ltd\.?(?!\w)",
                r"株式会社",
                r"有限会社",
                r"有限公司",
                r"股份有限公司",
                r"주식회사",
            ],
            "limitToDataSource": ["FWF"],
        },
        {"name": "Other", "description": "", "mapTo": "OTHER", "keywords": [], "limitToDataSource": ["FWF"]},
    ],
)
